apiVersion: v1
kind: Pod
metadata:
  name: pod-utilization
  labels:
    app: mytest-pod
spec:
  containers:
    - name: mytest-container
      image: nginx:1.29
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: 128Mi
          cpu: 250m
        limits:
          memory: 256Mi
          cpu: 500m

    - name: stress-container
      image: polinux/stress
      command: ["stress"]
      args: ["--cpu", "2", "--vm", "1", "--vm-bytes", "128M", "--timeout", "300s"]
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 400m
          memory: 256Mi
