apiVersion: v1
kind: Service
metadata: 
  name: service-container
# Before adding namespace in yaml file 
# We need to create namespace in VM using below commands
# kubectl get namespace --> It'll show all namespace's in VM
# kubectl config set-context --current --namespace=<insert-yournamespace-name-here>
# After running the yaml file, 
# We need it get into namespace environment to see pod and nodes status
# kubectl get pods -n yournamespace
  namespace: fake-production
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80